jest markdown test...
neofinancial/coverage-action pull request #13
Opened 2021-06-21 15:14 UTC by leah-is-offline

2021-06-22 15:39 UTC, iansu requested changes
This looks good but the formatting is not right. Run prettier on it.

2021-06-23 16:53 UTC, emmettcollings requested changes
Looks good, some very minor cleanup needed

2021-06-23 16:53 UTC, emmettcollings commented on src/construct-comment.ts
> +  //const baseUrl = process.env.NEXT_PUBLIC_BASE_URL
Should remove commented out code

2021-06-23 16:53 UTC, emmettcollings commented on src/quotes.ts
> +  "\"So I'll just put this in production and then you'll tell me if it's okay...right?\"",
You can use single quotes here too to avoid escaping double quotes.

2021-06-23 17:08 UTC, leah-is-offline commented on src/construct-comment.ts
> +  //const baseUrl = process.env.NEXT_PUBLIC_BASE_URL
Im just testing something right now

2021-06-23 18:45 UTC, iansu requested changes
Just some formatting issues. You should also avoid using capital letters in filenames so rename `Jest_logo.png` to `jest-logo.png`

2021-06-23 18:45 UTC, iansu commented on src/construct-comment.ts
> +    return `<img src="${  baseUrl  }/public/sadkris.png" width="30" height="30"/>`
There are lots of formatting issues in this file. Run prettier on it.

2021-06-23 20:04 UTC, leah-is-offline commented on src/construct-comment.ts
> +    return `<img src="${  baseUrl  }/public/sadkris.png" width="30" height="30"/>`
This file is being ignored because prettier re-formats the markdown in  a breaking way. I moved all the code that isn't markdown to a different file and formatted it

2021-06-23 21:37 UTC, BrendonLapp commented on .env.local
> +NEXT_PUBLIC_BASE_URL=http://localhost:3000
Missing a new line at the end of this file.

2021-06-28 20:45 UTC, emmettcollings commented on src/quotes.ts
> +const getQuote = async (): Promise<string> => {
Not sure if `floor()` or `random()` have anything async in them, this function might not need to be async

2021-06-29 14:45 UTC, emmettcollings requested changes
One more edit, then good to go

2021-06-29 14:45 UTC, emmettcollings commented on src/construct-comment.ts
> +  const inspiration = await getQuote()
We don't have to await this since it isn't async anymore

2021-06-29 16:52 UTC, emmettcollings approved these changes

2021-06-29 22:11 UTC, emmettcollings commented on src/quotes.ts
> +  "\"So I'll just put this in production and then you'll tell me if it's okay...right?\"",
```suggestion
  `"So I'll just put this in production and then you'll tell me if it's okay...right?"`,
```

2021-06-29 22:53 UTC, connkat approved these changes

2021-06-30 00:35 UTC, AdamTranquilla commented on src/construct-comment-utils.ts
> +    return '🥈';
Why :100: 🥇 🥈 with no :3rd_place_medal:? 

I feel like it would make more sense for 100% to be gold, then either include bronze OR to bump silver to 80% and add bronze as 70

2021-06-30 05:05 UTC, iansu approved these changes

2021-06-30 13:07 UTC, merged