Ch42386/create a comment
neofinancial/coverage-action pull request #4
Opened 2021-05-20 07:17 UTC by BrendonLapp

Test PR to see if comment posts

2021-05-20 20:41 UTC, iansu requested changes

2021-05-20 20:41 UTC, iansu commented on .prettierrc
> +  "printWidth": 80,
We generally use 120 for this setting.

2021-05-20 20:41 UTC, iansu commented on __tests__/main.test.ts
> +import { wait } from '../src/wait';
We generally put tests in a directory named `test`.

2021-05-20 20:41 UTC, iansu commented on action.yml
> +  using: 'node12'
I think this should be `node14`

2021-05-20 20:41 UTC, iansu commented on jest.config.js
> +  clearMocks: true,
You probably don't want to enable this or `verbose` by default.

2021-05-20 20:41 UTC, iansu commented on package.json
> +    "url": ""
The URL for this project is the URL of this GitHub repo.

2021-05-20 20:41 UTC, iansu commented on package.json
> +  "author": "Neo Financial Engineering",
This and `license` should go after `description`

2021-05-20 20:41 UTC, iansu commented on package.json
> +  "dependencies": {
Dependencies should go before devDependencies. Many of the things in devDependencies are actually dependencies and should be moved. Only things related to running tests, linting, compiling should be in devDependencies.

2021-05-20 20:41 UTC, iansu commented on tsconfig.json
> +    "compilerOptions": {
The indentation is wrong in this file.

2021-05-20 20:41 UTC, iansu commented on src/index.ts
> +import * as core from '@actions/core';
You should only import the functions you're using.

2021-05-20 20:41 UTC, iansu commented on src/index.ts
> +      `Lines hit: ${data.coverage.lines.hit} Lines found: ${data.coverage.lines.found}`
You have everything you need here to calculate the percentage.

2021-05-20 20:41 UTC, iansu commented on src/perform-commenting.ts
> +    try{
The indentation is wrong in this file.

2021-05-20 20:41 UTC, iansu commented on src/perform-commenting.ts
> +export const performCommenting = async( lines: Lines, functions: Functions, branches: Branches ): Promise<void> => {
All exports (except for types and interfaces) should go at the end of the file. This is also kind of an awkward name. How about just `makeComment` or something like that?

2021-05-20 20:41 UTC, iansu commented on src/perform-commenting.ts
> +        const botComment = comments.data.find(comment => comment.user?.login === "github-actions[bot]");
This will find the first comment left by *any* GitHub Action and overwrite it. The way I've handled this in the past is by including a comment at the end of my message like `<!-- coverage-action-comment -->`

2021-05-20 20:41 UTC, iansu commented on src/wait.ts
> +export async function wait(milliseconds: number): Promise<string> {
I'm not sure what the purpose of this function is but there are easier ways to do this. The easiest way available in Node 14 is probably this:

```ts
import { promisify } from 'util';

const wait = promisify(setTimeout);
```

2021-05-21 19:31 UTC, iansu requested changes
You missed one comment about using `node14` in action.yml and you forgot to rename `__tests__` to `test`.

2021-05-21 20:13 UTC, BrendonLapp commented
We can't use node14 as GitHub actions only support node12. The __tests__ folder has been renamed to test

2021-05-21 20:25 UTC, BrendonLapp commented on action.yml
> +  using: 'node12'
Node14 isn't supported in GitHub actions. We have to use node 12

2021-05-25 19:56 UTC, iansu submitted a review, later dismissed

2021-05-25 20:35 UTC, emmettcollings commented on action.yml
> +    description: Github token not used yet
Description of this might need a change

2021-05-25 21:34 UTC, emmettcollings commented on .gitignore
> +build
Ignoring the build folder here will require the user to compile the action in their workflow before using it. If we compile it ourselves and include the build folder they can skip that step, speeding things up.

2021-05-25 21:35 UTC, emmettcollings commented on .husky/.gitignore
> +_
Don't think this is doing anything anymore

2021-05-25 21:39 UTC, emmettcollings commented on src/lcov.d.ts
> +declare module 'lcov-parse';
Is this doing anything different than `declarations.d.ts`? They have the same contents.

2021-05-25 22:40 UTC, BrendonLapp commented on src/lcov.d.ts
> +declare module 'lcov-parse';
lcov.d.ts is removed

2021-05-25 22:40 UTC, emmettcollings approved these changes

2021-05-26 15:33 UTC, leah-is-offline approved these changes

2021-05-26 15:38 UTC, connkat commented on src/make-comment.ts
> +    if (context.payload.pull_request == null) {
`===` is always preferred over `==`. double can be a bit foggy, especially with types. There are definitely use cases for double over triple, but I would say it is safe to default to triple with both typescipt and javascript because it is more likely what you are looking for.

2021-05-26 16:23 UTC, merged